Feature/pt 12/setup ap is
samresh9/protectedText pull request #13
Opened 2023-05-19 11:22 UTC by samresh9

Fixes #12 
Setup mongodb atlas for two differnet instances production and development.
Design api for Get/notes Post/notes and Put/notes

2023-05-19 14:14 UTC, therj requested changes

2023-05-19 14:14 UTC, therj commented on routes/notesRoutes.js
> +    }
This is a good opportunity to introduce validation as a middleware.
Explore `joi` or `express-validator`...

2023-05-19 14:14 UTC, therj commented on routes/notesRoutes.js
> +    }
Same as above, validation as a middleware.

2023-05-19 19:55 UTC, therj requested changes

2023-05-19 19:55 UTC, therj commented on routes/notesRoutes.js
>      }
This should belong to middleware.

2023-05-19 19:55 UTC, therj commented on routes/notesRoutes.js
> +];
Move all validations to a different file or folder. 
Example: /validations/notesRoutes.js -> it could have 2 functions: postNotes, putNotes (= validationRules). Import them to notesRoutes and use as middleware... For this case, it could also export a single validator function - that's fine.

2023-05-19 20:11 UTC, samresh9 commented on routes/notesRoutes.js
>      }
I tried throwing error but my errorHandler middleware is not handling it

2023-05-19 21:20 UTC, samresh9 commented on routes/notesRoutes.js
>      }
I found out that if the function is asynchronous then direct throw new Error wont be handled by errorHandler.For that to work I found out that we should use try catch and next. I am still not clear. But using throw I am not able to give the format
as I want.

2023-05-21 05:49 UTC, therj commented on routes/notesRoutes.js
>      }
@samresh9 Correct! 
Handler (middlewares or route handlers) gets 3 things: request, response, next. If you do next(error) where error is of Error instance [error = new Error("Some message") or error thrown from another function], it'll directly go to error handler instead of the next middleware.

Error handler is special kind of handler, it has 4 parameters while all other middlewares have 3.
Check this documentation: https://expressjs.com/en/guide/error-handling.html

2023-05-21 05:52 UTC, therj requested changes

2023-05-21 05:52 UTC, therj commented on routes/notesRoutes.js
>      }
This also needs to be within the middleware. If you use middleware to validate and again inside the route, it make no sense of having the middleware. Same for the PUT route.

You may need a validator function (which you've already done) and another middleware function that takes req, res, next.

2023-05-21 18:10 UTC, samresh9 commented on routes/notesRoutes.js
>      }
Please check my lastest commit and changes I tried what you reviewed.

2023-05-22 03:47 UTC, therj requested changes

2023-05-22 03:47 UTC, therj commented on config/development.js
> +  dbConnection: process.env.MONGO_CONNECTION_URI_DEV,
This will get confusing, use default.js for this setting - use consistent environment variable.
```js
dbConnection: {
   url: "<>",
  options: {... }
}
```

2023-05-22 03:47 UTC, therj commented on index.js
> +connectMongoDb();
connectMongoDb returns a promise, so program will continue running further. Only when db connection fails (which is not immediate and may take upwards of 30s), the program will crash. This may be difficult to trace when it happens.

Current implementation is fine as long as you understand what's happening. If you want to keep things sequential, create an IIFE (immediately invoked function expression) as you can not await promises outside the async functions.

2023-05-22 03:47 UTC, therj commented on middlewares/handleErrorsMiddleware.js
>    res.json({
There shouldn't be next after the last middleware that returns the error response!

2023-05-22 03:47 UTC, therj commented on middlewares/validationErrorsHandlerMiddleware.js
> +    throw err;
I think ES Lint should complain about throwing a plain object... An error object will only contain message (in addition to default name). If you need additional properties, you'll have to define a new class that extends the built-in Error class.

2023-05-22 03:47 UTC, therj commented on routes/notesRoutes.js
> +      }
This should be gone from here?

2023-05-22 04:09 UTC, samresh9 commented on routes/notesRoutes.js
> +      }
yeah this works fine but the statuscode is always 500 so I tried sending a object

2023-05-22 04:17 UTC, samresh9 commented on config/development.js
> +  dbConnection: process.env.MONGO_CONNECTION_URI_DEV,
I have two db url for production and development so should I make it still in default.js or respective environment

2023-05-26 15:57 UTC, samresh9 commented on src/index.js
Can I use them as a function and register the event or should I use them as a global middleware?

2023-05-26 17:27 UTC, therj requested changes

2023-05-26 17:27 UTC, therj commented on src/middlewares/validationErrorsHandlerMiddleware.js
> +    throw err;
If you're only passing the message, new Error itself would be enough.

**Not requesting change here, keep the code and think about it.** 

You may intend to extend later or you may have use cases around the error name itself.

FYI, error.array may have multiple errors. There should be some way to validate it, right?

2023-05-26 17:27 UTC, therj commented on src/routes/notesRoutes.js
> +      });
Nested ifs are difficult to take care of in long run if updated. Shorten them.

```
if(existingSite?.hasContent === hashContent) { change In data false case}

if (existingSite) {existing site and new content}

// create new case

```

**Great job that you don't have else for creating a note!** (ES Lint should also point that)

2023-05-26 17:27 UTC, therj commented on src/utils/handleExceptionAndRejections.js
> +};
Leave `process.on("uncaughtException", uncaughtExceptionHandler)` in the entry file. 

uncaughtExceptionHandler is the callback function you're using here. Rename the

```js
const uncaughtExceptionHandler = (err) => {
    logger.error(err.name, err.message);
    logger.info("Uncaught exception shutting down");
    ...
}
```

2023-05-26 17:27 UTC, therj commented on src/utils/handleExceptionAndRejections.js
> +    logger.info("Uncaught exception shutting down");
Should be logger.error. Shutting down is not a info message.
I believe logger takes first parameter as message and second as object.

logger.error("err.message or anything custom", {other things as object properties})

2023-05-26 17:27 UTC, therj commented on src/index.js
They're not middleware. They directly attach to node process (not express app)

2023-05-26 17:27 UTC, therj commented on src/routes/notesRoutes.js
> +  handleValidationErrors,
There shouldn't be two middlewares to validate data in body and return error if invalid (it's one single feature).. Maybe create a wrapper function that takes validator schema and return another function that gets executed at middleware. (They're called higher order functions, if you want to lookup)

2023-05-28 12:22 UTC, therj requested changes

2023-05-28 12:22 UTC, therj commented on src/middlewares/validationErrorsHandlerMiddleware.js
> +      const err = new ValidationError(errorMessage);
Are you sure you want errorMessage to be a string? errorMessages array wouldn't be enough?

2023-05-28 12:22 UTC, therj commented on src/middlewares/validationErrorsHandlerMiddleware.js
> +    return next();
No return, just `next()`

2023-05-28 12:22 UTC, therj commented on src/routes/notesRoutes.js
> +  handleValidationErrors(userDataValidateChain),
Rename to something understandable... I'm assuming that we'll be able to re-use schemaValidator for other routes dynamically

- schemaValidator(userSchema)
- schemaValidator(notesSchema)

2023-05-28 12:22 UTC, therj commented on src/utils/handleExceptionAndRejections.js
> +  logger.error("Uncaught exception shutting down");
logger.error("Uncaught exception shutting down", {message: err.message});

2023-05-29 01:45 UTC, therj requested changes

2023-05-29 01:45 UTC, therj commented on src/middlewares/validationErrorsHandlerMiddleware.js
>      // this.statusCode = statusCode;
Keep passing (message, errors). Do not do manipulation here, just assign.
this.message = message
this.errors = errors

Message should be made string before sending to this method.

2023-05-29 01:45 UTC, therj commented on src/routes/notesRoutes.js
> +    }
This should return 404 error.

2023-05-29 01:45 UTC, therj commented on src/middlewares/validationErrorsHandlerMiddleware.js
> +      return next(err);
You're doing next(err), but 500 handler does not have {errors: ..} property in the response - either return from here, or have errors property in 500 handler.

Errors from new ValidationError() are simply lost.

2023-05-29 01:45 UTC, therj commented on src/validations/notesRoutesValidations.js
>  ];
Definitely not saveSchema. noteSchema (if both put/post use it) else, postNoteSchema or putNoteSchema.

2023-05-31 05:10 UTC, therj requested changes
Change required with Validation Error (and maybe 500 handler as well)

2023-05-31 05:10 UTC, therj commented on src/middlewares/validationErrorsHandlerMiddleware.js
>      this.name = "ValidationError";
I think we want both message, and errors and a parameter!

2023-05-31 05:10 UTC, therj commented on src/middlewares/validationErrorsHandlerMiddleware.js
> +      const err = new ValidationError(errorMessage);
And pass message and errors array to ValidationError.

2023-05-31 05:10 UTC, therj commented on src/routes/notesRoutes.js
> +      return res.status(404).json({ errorMessage: "Url not found" });
Just make sure your error response object is consistent on 404 and validation.

2023-05-31 17:07 UTC, therj requested changes

2023-05-31 17:39 UTC, samresh9 commented
@therj #13 
when I send both error and message and send error to 500 handler the response is given in this format.
Is this valid or just sending the message to 500 handler is good?
{
"message": "Encrypted Content is required,Hash Content is required",
"statusCode": 400,
"error": {
"message": "Encrypted Content is required,Hash Content is required",
"errors": [
{
"type": "field",
"msg": "Encrypted Content is required",
"path": "content",
"location": "body"
},
{
"type": "field",
"msg": "Hash Content is required",
"path": "hashContent",
"location": "body"
}
],
"name": "ValidationError"
},
"stackTrace": "Error\n at E:\ProtectedText\protectedText\src\middlewares\validationErrorsHandlerMiddleware.js:25:19\n at processTicksAndRejections (node:internal/process/task_queues:96:5)"
}

2023-05-31 17:52 UTC, therj requested changes

2023-05-31 17:52 UTC, therj commented on src/middlewares/handleErrorsMiddleware.js
> +    error,
Since we have decided to throw a custom error.. You'll receive the same here.

```
message: error.message,
errors: error.errors,
```

2023-05-31 17:52 UTC, therj commented on src/middlewares/validationErrorsHandlerMiddleware.js
>        const errorMessage = errors.array().map((error) => error.msg);
Since you'd have errors as an array of object for details.. You may want to keep errorMessage lightweight and user friendly string.. Try for a few inputs, if you can not get to particular state of errors use debugger to modify variables midway to get those.

2023-05-31 18:22 UTC, samresh9 commented
@therj 
{
    "message": "Encrypted Content  is required,Hash Content is required",
    "statusCode": 400,
    "stackTrace": "ValidationError: Encrypted Content  is required,Hash Content is required\n    at E:\\ProtectedText\\protectedText\\src\\middlewares\\validationErrorsHandlerMiddleware.js:23:19\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
}
This is how my latest commit gives error Is this valid?

2023-05-31 18:56 UTC, samresh9 commented
this is accoroding to my latest committ

{
    "message": "Encrypted Content  is required,Hash Content is required",
    "statusCode": 400,
    "errors": [
        {
            "type": "field",
            "msg": "Encrypted Content  is required",
            "path": "content",
            "location": "body"
        },
        {
            "type": "field",
            "msg": "Hash Content is required",
            "path": "hashContent",
            "location": "body"
        }
    ],
    "stackTrace": "ValidationError: Encrypted Content  is required,Hash Content is required\n    at E:\\ProtectedText\\protectedText\\src\\middlewares\\validationErrorsHandlerMiddleware.js:24:19\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
}

2023-06-03 07:35 UTC, therj requested changes

2023-06-03 07:35 UTC, therj commented on src/routes/notesRoutes.js
> +        .json({ errorMessage: `Not Found ${req.method} ${req.originalUrl}` });
.json({message : "Note not found ${...}.."}). This makes it consistent since all other errors have message as key - not errorMessage (including 404 handler).

2023-06-03 07:35 UTC, therj commented on src/utils/handleExceptionAndRejections.js
> +  logger.error(err.message);
Remove this line!

2023-06-04 13:40 UTC, therj approved these changes

2023-06-04 13:41 UTC, merged