Feature/pt 14/api documentation
samresh9/protectedText pull request #21
Opened 2023-06-06 10:02 UTC by samresh9

Fixes #14 
Setup Swagger

2023-06-06 23:10 UTC, therj requested changes

2023-06-06 23:10 UTC, therj commented on src/models/notesModel.js
>      },
This is an interesting problem to have!

Change in schema makes existing data useless, or worse conflicting.
We already have notes in db - we do not want to lose that. 
Create a migration script that moves existing data into new format, put migration scripts in a separate folder - {projectRoot}/migrations/YYYYMMDD_script_name.js.

2023-06-07 04:04 UTC, samresh9 commented on src/models/notesModel.js
>      },
I faced the problem but had no I idead about creating a separate file for migration I ran command on  mongoshell for $rename fieldName.
db.notes.updateMany({},{$rename:{'noteId':'id', 'content':'encryptedContent', 'hashContent':'hash'}})
Is this a wrong approach?

2023-06-08 17:01 UTC, therj commented on src/models/notesModel.js
>      },
The script should be tested in dev environments, and everyone should be able to replicate the data migration anywhere and everywhere.

Create the script.. Deploy the old commit, create notes, try migrating again. Now, you've even more interesting problem as you will have a mix of old and new structure of data. 🧐

2023-06-08 20:19 UTC, therj commented on src/routes/notesRoutes.js
> + * /api/notes:
Let's keep /api/ out of route name on swagger.

2023-06-08 20:19 UTC, therj commented on src/routes/notesRoutes.js
> + * /api/notes/{id}:
+1
Let's keep /api/ out of route name on swagger.

2023-06-10 08:10 UTC, samresh9 commented on src/models/notesModel.js
>      },
Do migrating means transforming old format to new and create new data or modifying the old data?
and by default  _v: 0 is present for both new and old format. Should I manually change the _v vlaue when creating new schema data?

2023-06-10 08:33 UTC, therj commented on src/models/notesModel.js
>      },
New data can have _v: 1,  old can have _v: 0. Both can co-exist. This is just one way to do things, but you can just write script to migrate based on field name, if doc.noteId, replace the document - else (node.id) let it be.

2023-06-12 14:21 UTC, therj approved these changes

2023-06-12 14:21 UTC, merged