PT-23: Setup Unit Test for sample function and enctypt decrypt handler functions using Jest and Chai
samresh9/protectedText pull request #24
Opened 2023-06-15 18:52 UTC by samresh9

Fixes #23 
Setup unit testing using a sample function from the utils and also with encrypt decrypt function handler

2023-06-15 18:59 UTC, therj commented
1. Delete testHelper.js and testHelper.spec.js file
2. Move encryptDecryptHandler.spec.js to tests/utils/

2023-06-15 19:14 UTC, therj requested changes

2023-06-15 19:14 UTC, therj commented on tests/encryptDecryptHandler.spec.js
> +const { expect } = require("chai");
Let's stick to assertions with Jest for now. Will switch to chai assertions if and when required.

2023-06-15 19:14 UTC, therj commented on tests/encryptDecryptHandler.spec.js
> +  });
Avoid nested describe block..

describe("encryptData", ()=>{
it("should encrypt data if note and secret is passed", ()=>{

})

it("should throw error if secret key is null", ()=>{
})

})

Since note and  secret key can be shared across the cases, define them inside describe, and set value inside the beforeEach() block (not really needed for this use case, but do it as a norm).

2023-06-15 19:14 UTC, therj commented on tests/encryptDecryptHandler.spec.js
> +      expect(decryptedData).to.equal("This is a secret note");
Do this same thing on encryption as well.. The tests should break when encryption is changed to anything from AES.

2023-06-15 19:18 UTC, therj commented
Include cases for failure and when error is expected.

https://jestjs.io/docs/expect#tothrowerror

2023-06-15 20:43 UTC, samresh9 commented on tests/encryptDecryptHandler.spec.js
> +      expect(decryptedData).to.equal("This is a secret note");
how to check the encryption algorithm as AES?, using mock?

2023-06-15 21:22 UTC, therj requested changes
testHelper.js is not deleted.

2023-06-15 21:22 UTC, therj commented on tests/utils/encryptDecryptHandler.spec.js
> +    expect(encryptedData).not.toBe(note);
Not necessary to check what it is NOT when you're also checking what is it.

2023-06-15 21:22 UTC, therj commented on tests/utils/encryptDecryptHandler.spec.js
> +    expect(decryptData(encryptedData, secretKey)).toBe(note);
Keep the encrypted data as a value in variable. It's okay to bake in in tests. This check will break if decryptData has error, but this is not test for that function.

expect(encryptedData).toBe(encryptedNote);

2023-06-15 21:22 UTC, therj commented on tests/utils/encryptDecryptHandler.spec.js
> +    }).toThrow();
toThrow any specific message?

2023-06-15 21:22 UTC, therj commented on tests/utils/encryptDecryptHandler.spec.js
> +    const decryptedData = decryptData(encryptedData, secretKey);
Do not couple encryption decryption while your UNIT to test is only one of them.

2023-06-15 21:22 UTC, therj commented on tests/utils/encryptDecryptHandler.spec.js
> +    const note = "This is a secret note";
Make it consistent with encrypt block

2023-06-15 21:22 UTC, therj commented on tests/utils/encryptDecryptHandler.spec.js
> +    expect(typeof hashedData).toBe("string");
consistency is missing.

type check is not enough. Check against expected value.

2023-06-15 21:22 UTC, therj commented on tests/utils/encryptDecryptHandler.spec.js
> +    expect(encryptedData).not.toBe(note);
Add jest.spyOn - to check crypto AES encrypt/decrypt is called once with expected params.

2023-06-16 04:02 UTC, therj commented on tests/encryptDecryptHandler.spec.js
> +      expect(decryptedData).to.equal("This is a secret note");
Don't use mock, use spy instead.. Spy will call the actual function and you'll know when it's called. Mock will override. We don't want to override.

2023-06-16 14:05 UTC, therj requested changes

2023-06-16 14:05 UTC, therj commented on tests/utils/encryptDecryptHandler.spec.js
> +    encryptSpy.mockRestore();
restore should go to afterEach

2023-06-16 14:05 UTC, therj commented on tests/utils/encryptDecryptHandler.spec.js
> +    const encryptSpy = jest.spyOn(CryptoJS.AES, "encrypt");
spy setup should go to beforeEach

2023-06-16 14:05 UTC, therj commented on tests/utils/encryptDecryptHandler.spec.js
> +    expect(encryptedData).toBeTruthy();
Replace the two lines below with actual value check! 
```
expect(typeof encryptedData).toBe("string");
expect(encryptedData).toBeTruthy();
```

2023-06-16 14:05 UTC, therj commented on tests/utils/encryptDecryptHandler.spec.js
> +    }).toThrow(TypeError);
I think there is error text as well, not just TypeError, validate.

2023-06-16 14:05 UTC, therj commented on tests/utils/encryptDecryptHandler.spec.js
> +  it("should call CryptoJS.AES.decrypt with expected params", () => {
Leave a blank line before it.

2023-06-16 14:05 UTC, therj commented on tests/utils/encryptDecryptHandler.spec.js
> +    decryptSpy.mockRestore();
Same feedback as above.

2023-06-16 14:05 UTC, therj commented on tests/utils/encryptDecryptHandler.spec.js
> +    expect(decryptedData).toBe(note);
Check for value.

2023-06-16 14:05 UTC, therj commented on tests/utils/encryptDecryptHandler.spec.js
> +    expect(typeof hashedData).toBe("string");
expect(hadhedData).toBe(expectedHash) is enough. String would already be checked there. type check in unnecessary.

2023-06-16 14:13 UTC, samresh9 commented on tests/utils/encryptDecryptHandler.spec.js
> +    encryptData(note, secretKey);
@therj  the encryptData value changes everytime we run it even though we pass the same value so the output is not constant.

2023-06-16 14:23 UTC, samresh9 commented on tests/utils/encryptDecryptHandler.spec.js
> +    expect(decryptedData).toBe(note);
@therj 
the value is in note variable. Is that okay?

2023-06-16 15:22 UTC, therj requested changes

2023-06-16 15:22 UTC, therj commented on tests/utils/encryptDecryptHandler.spec.js
>        encryptData(note, secretKey);
Straight up pass encryptData(note, null). No need to change the value of secretKey.

2023-06-16 15:22 UTC, therj commented on tests/utils/encryptDecryptHandler.spec.js
>        decryptData(note, secretKey);
decryptData(note, null);

2023-06-16 15:23 UTC, therj commented on tests/utils/encryptDecryptHandler.spec.js
> +    expect(decryptedData).toBe(note);
No need to check type.

2023-06-16 16:25 UTC, samresh9 commented on tests/utils/encryptDecryptHandler.spec.js
> +    expect(encryptedData).toBeTruthy();
@therj the encryptData value changes everytime we run it even though we pass the same value so the output is not constant. so I cannot have the actual value to check

2023-06-16 16:47 UTC, therj requested changes

2023-06-16 16:47 UTC, therj commented on tests/utils/encryptDecryptHandler.spec.js
> +    CryptoJS.AES.encrypt(note, secretKey).toString();
Wouldn't it make this test cases senseless?
Revert. The output from encryptData would be encrypted value.

Use this as a **reference**:
```
expectedDecryptedValue = note
responsefromencryptData = encryptData(note, secretKey);
actualDecrptredValue = CryptoJS.AES.decrypt(responsefromencryptData, secretKey)
expect(actualDecrptredValue).toBe(expectedDecryptedValue)
```

2023-06-16 16:47 UTC, therj commented on tests/utils/encryptDecryptHandler.spec.js
> +    );
Same as above comment!

2023-06-16 16:47 UTC, therj commented on tests/utils/encryptDecryptHandler.spec.js
>      expect(decryptSpy).toHaveBeenCalledWith(encryptedData, secretKey);
merge call count and params, (decryptSpy) to have been called once with

2023-06-16 17:04 UTC, therj commented on tests/utils/encryptDecryptHandler.spec.js
> +    expect(encryptedData).toBeTruthy();
> @therj the encryptData value changes everytime we run it even though we pass the same value so the output is not constant. so I cannot have the actual value to check

Decrypt with crypto within the test case and compare decrytped value with originally passed value.

2023-06-17 18:03 UTC, samresh9 commented on tests/utils/encryptDecryptHandler.spec.js
>      expect(decryptSpy).toHaveBeenCalledWith(encryptedData, secretKey);
@therj 
I didn't found Jest assertion method for toHaveBeenCalledOnceWith() defined directly

2023-06-17 18:25 UTC, therj requested changes

2023-06-17 18:25 UTC, therj commented on tests/utils/encryptDecryptHandler.spec.js
> +    expect(decryptSpy).toHaveBeenCalledWith(responsefromencryptData, secretKey);
weUseCamelCase, don't we? And that variable name may not be appropriate.

**Use as a reference meant use as a reference, nothing more!**

2023-06-17 18:25 UTC, therj commented on tests/utils/encryptDecryptHandler.spec.js
> +    const expectedDecryptedValue = note;
It's already there and you're not going to modify, why need to duplicate?

2023-06-17 18:25 UTC, therj commented on tests/utils/encryptDecryptHandler.spec.js
> +    expect(actualDecrptredValue).toBe(expectedDecryptedValue);
Same as feedback below.

2023-06-17 18:27 UTC, therj requested changes

2023-06-17 18:27 UTC, therj commented on tests/utils/encryptDecryptHandler.spec.js
> +    const hash = CryptoJS.SHA512(note, secretKey).toString();
Call the hashData function you wrote. It is testing CryptoJS, we want to test our code, and only our code!

2023-06-17 18:28 UTC, therj commented
@samresh9 Please add reply to comments, or mark them resolved if it's clear and already fixed.

2023-06-17 19:09 UTC, therj approved these changes

2023-06-18 09:01 UTC, therj approved these changes

2023-06-18 09:02 UTC, merged