PT-22: Add readme.md
samresh9/protectedText pull request #25
Opened 2023-06-17 18:01 UTC by samresh9

Fixes #22 
Added documentation in README.md

2023-06-17 18:21 UTC, therj requested changes

2023-06-17 18:21 UTC, therj commented on README.md
> +You can access the development version of the project at [Development Url](https://protected.samresh.com.np/).
Just call it live url. Will point this url to point to main branch.
Mention development url in same sentence.

2023-06-17 18:21 UTC, therj commented on README.md
> +3. Create a `.env` file at the root of your project.
Clone sample.env and fill the values.

2023-06-17 18:21 UTC, therj commented on README.md
> +
This should be in sample.env if required. Omit from readme.

2023-06-17 18:21 UTC, therj commented on README.md
> +The base URL for all API endpoints is: `https://protected.samresh.com.np`
API Documentation will load at /api-docs. Is also available at https://protected.samresh.com.np/api-docs. It can be disabled by switching some flag in env, right? We'd like to disable in PROD.

2023-06-17 18:21 UTC, therj commented on README.md
> +## Endpoints
Remove this entire section - this is what swagger documentation is for.

2023-06-17 18:21 UTC, therj commented on README.md
> +MONGO_CONNECTION_URI= your-mongodb-uri
Above text should work as a reminder for development. Maybe explain if some variables are absolutely, and others are not (log related stuffs have default values, but mongodb url must be configured...). Rest should be inferred from sample.env

2023-06-18 09:58 UTC, samresh9 commented on README.md
> +The base URL for all API endpoints is: `https://protected.samresh.com.np`
@therj 
Currently I we have no such conditions to disable swagger. Do I need to add one ?

2023-07-02 13:16 UTC, therj approved these changes

2023-07-02 13:17 UTC, merged