Feature/pt 34/setup vite react
samresh9/protectedText pull request #46
Opened 2023-08-14 21:34 UTC by samresh9

- setup react vite app with default home page
- setup shared eslint config between apps

2023-08-15 05:56 UTC, therj requested changes

2023-08-15 05:56 UTC, therj commented on packages/eslint-config-custom/index.js
> +    ],
Move all rules, not just prettier.

2023-08-15 05:56 UTC, therj commented on packages/eslint-config-custom/index.js
>    },
Why should devDependencies be allowed?

2023-08-15 20:22 UTC, samresh9 commented on packages/eslint-config-custom/index.js
> +    ],
Its not working, when I moved all the rules to the shared config the rules are not extended and error occurs.

2023-08-22 14:13 UTC, therj requested changes
changes required around es lint misconfig.

2023-08-22 14:13 UTC, therj commented on packages/eslint-config-custom/index.js
> +  plugins: ["react-refresh", "import"],
These plugins got moved to frontend.

2023-08-22 14:13 UTC, therj commented on packages/eslint-config-custom/index.js
> +    ],
This should be front end specific

2023-08-22 14:13 UTC, therj commented on apps/frontend/.eslintrc.cjs
> +  ignorePatterns: ["dist"],
This is already in customconfig

2023-08-22 17:15 UTC, therj commented on apps/frontend/.eslintrc.cjs
> -  },
Where did the react version go?

2023-08-22 17:17 UTC, therj commented on apps/frontend/.eslintrc.cjs
> -  },
"eslint-plugin-import": "^2.27.5", should come to frontend plugins (is it required?)

2023-08-22 17:17 UTC, therj commented on apps/frontend/.eslintrc.cjs
> -  },
react settings went to shared config, why?

2023-08-22 17:59 UTC, samresh9 commented on apps/frontend/.eslintrc.cjs
> -  },
> -
previously it was showing warning in lint but now reinstalling all the packages fixed it
so moved back to frontend.

2023-08-24 02:19 UTC, therj commented on packages/eslint-config-custom/package.json
> +    "eslint-plugin-import": "^2.28.1",
eslint-plugin-import sets up errors for ESM syntax, used at plugins: ["import"].

For now, this only affects the frontend as backend and packages use CJS.

2023-08-24 02:20 UTC, therj commented on packages/eslint-config-custom/package.json
> +    "eslint-plugin-import": "^2.28.1",
https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/prefer-default-export.md

2023-08-25 03:13 UTC, therj approved these changes

2023-08-25 03:14 UTC, merged