Feature/pt 4/setup debugger and logger
samresh9/protectedText pull request #8
Opened 2023-05-11 17:38 UTC by samresh9

Added Morgan for http request logger and stored logs to a httploger file.
Added Winston for other logging 
Setup lauch.json for Debugging but still getting some errors.

2023-05-11 18:38 UTC, therj requested changes

2023-05-11 18:38 UTC, therj commented on .vscode/launch.json
> +
The json is not formatted, and end of file is missing a newline.

In next push, it should be already detected with your new husy pre-commit hook.

2023-05-11 18:38 UTC, therj commented on index.js
> +// eslint-disable-next-line import/no-extraneous-dependencies
This shouldn't be required anymore and morgan is already being used below.

(And never disable lint rules, unless as an exception).

2023-05-11 18:38 UTC, therj commented on index.js
>      console.log("Database Connected");
Awesome. Remove the console now. And set eslint rules to give error/warn for console statements.

2023-05-11 18:38 UTC, therj commented on log/logger.js
> +  ],
log level, pretty print enable/disable and transport (= file/console/) should come from configuration file or env.

2023-05-11 18:38 UTC, therj commented on log/logger.js
> +// eslint-disable-next-line import/no-extraneous-dependencies
No. We don't do this.

2023-05-11 18:38 UTC, therj commented on package.json
>      "lint-fix": "eslint . --fix",
use `lint:fix` instead of `lint-fix`.
We'll discuss later on why!

2023-05-12 12:20 UTC, samresh9 commented on .vscode/launch.json
> +
Eslint is not formatting json files

2023-05-12 12:48 UTC, therj commented on .vscode/launch.json
> +
Noted. ES Lint won't fix json files out of the box. No need to setup as this is probably the only json file in the project. Still, consider formatting (prettier / vs code built-in formatter).

2023-05-12 13:21 UTC, samresh9 commented on log/logger.js
> +  ],
please can you provide some refrence on how to use configuration file

2023-05-12 13:25 UTC, therj commented on log/logger.js
> +  ],
Package: https://www.npmjs.com/package/dotenv
In `.env` file at root:
``` 
LOG_LEVEL = info
```

Initialize dotenv at top of the entry file (index.js?) with `require('dotenv').config()`

Now, `process.env.LOG_LEVEL` will contain the value `info` anywhere in the project.

2023-05-12 15:41 UTC, therj requested changes

2023-05-12 15:41 UTC, therj commented on .eslintrc.js
> +      },
This effectively allows console.info/warn/error. I don't think that's intended.

2023-05-12 15:41 UTC, therj commented on .eslintrc.js
> +    "import/no-extraneous-dependencies": "off",
You need to really explain why you'd keep unused imports and dependencies in the code, or remove these lines and fix your code instead.

PS. In some cases of callback functions, you'll need the second parameter but not the first one. For those cases, you can add eslint rule to allow unused variables that start with underscore: _

2023-05-12 15:41 UTC, therj commented on package.json
> +    "nodemon": "^2.0.22",
nodemon should have been a dev dependency.

2023-05-12 15:41 UTC, therj commented on index.js
> +const morgan = require("morgan");
Order of imports:
1. alphabetical package imports
2. import from other files
3. No unnecessary blank lines in between (lines between packages and project file imports is fine)

2023-05-12 19:57 UTC, samresh9 commented on .eslintrc.js
> +    "import/no-extraneous-dependencies": "off",
Now when I removed   "import/no-extraneous-dependencies": "off", it no longer shows the error

2023-05-14 13:03 UTC, therj commented on log/logger.js
> +  ],
Use single transport. Use dotnev for "CONSOLE" vs "FILE". Use LOG_FILE_PATH, defaults to "./logs/<filename>.log".

2023-05-14 16:48 UTC, samresh9 commented on log/logger.js
> +  ],
resolved

2023-05-14 18:24 UTC, therj requested changes

2023-05-14 18:24 UTC, therj commented on log/logger.js
> +}
Use switch case.
process.env.APP_LOG_DESTINATION: FILE or STDOUT (aka console) or stream.

```js
// use this variable in line 6 and inside file transport
const logLevel = process.env.LOG_LEVEL || "info";

switch (process.env.APP_LOG_DESTINATION) {
  case "FILE":
    logger.add(new transports.File({ filename: process.env.LOG_FILE_PATH, level: logLevel }));
    break;
  default:
    logger.add(new transports.Console());
    break;
}
```

2023-05-16 08:05 UTC, samresh9 commented
When Using config file should I import the value for logLevel from .env or should I directly include the value in config files?

2023-05-16 17:43 UTC, therj commented
> When Using config file should I import the value for logLevel from .env or should I directly include the value in config files?

It's  okay to use directly inside the config/<env>.js file - if it does not has to be a secret.

2023-05-16 17:50 UTC, samresh9 commented
Are all the problems resolved for merging this branch to develop?

2023-05-16 17:54 UTC, therj requested changes

2023-05-16 17:54 UTC, therj commented on log/logger.js
> +switch (config.get("appLogDestination")) {
You chose to pull from config/ file, where is the file?

2023-05-16 17:55 UTC, samresh9 commented on log/logger.js
> +switch (config.get("appLogDestination")) {
should we gitignore config files?
sorry I gitignored it

2023-05-16 17:57 UTC, therj commented on log/logger.js
> +switch (config.get("appLogDestination")) {
No. Never.
It's assumed you only keep the values that are okay to expose in config file, secrets should be inn .env file and it will be included in gitignore.

2023-05-16 18:16 UTC, therj commented on log/logger.js
> +const logLevel = config.get("logLevel") || "info";
logLevel shouldn't be at global level on config file, how's the file structured?

Expected:

```js
{
logger: {
  level: true|false,
  }
}
```

Fetch with 
```
logLevel = config.get("logger.logLevel")
```

Or

```
loggerConfig = config.get("logger");
logLevel = loggerConfig.level
```

2023-05-16 18:39 UTC, samresh9 commented on log/logger.js
> +const logLevel = config.get("logLevel") || "info";
I commited the change but can you explain more if my changes are wrong

2023-05-16 18:53 UTC, therj requested changes

2023-05-16 18:53 UTC, therj commented on config/default.js
> +  appLogDestination: "console",
Keep these properties inside logger.

```js
module.exports = {
  logger: {
    level: "info",
   pretty: true,
   destination: "console" // or FILE,
   filePath: "./log/..."
  },
```

2023-05-16 18:53 UTC, therj commented on config/development.js
> +};
**development.js has to be in same structure of default.js!!**

2023-05-16 18:53 UTC, therj commented on config/production.js
> +  appLogDestination: "FILE",
Same as development.js

2023-05-16 19:06 UTC, therj requested changes

2023-05-16 19:06 UTC, therj commented on log/logger.js
> +    config.get("logger.prettyPrint") === "true" ? prettyPrint() : prettyPrint()
Use config.get after require statements, not in between the code.

2023-05-16 19:06 UTC, therj commented on log/logger.js
> +switch (config.get("logger.appLogDestination")) {
Same as other one.

2023-05-16 19:09 UTC, therj reviewed
If other configs also use the same config from default.js, not need to have the property elsewhere (development/production.js)

2023-05-16 19:18 UTC, therj commented on log/logger.js
> +const logLevel = config.get("logLevel") || "info";
It's not necessary to call a property `logLevel`, for example, since it's already inside the `logger: ` key

2023-05-16 19:29 UTC, therj commented on config/default.js
> +    appDestination: "console",
camelCase.

What is appDestination? Just `destination`, or `logDestination`..

2023-05-16 19:30 UTC, samresh9 commented
> If other configs also use the same config from default.js, not need to have the property elsewhere (development/production.js)

is it that if NODE_ENV is not set in the environment then logger uses value of development.js?

2023-05-16 19:31 UTC, therj commented
> > If other configs also use the same config from default.js, not need to have the property elsewhere (development/production.js)
> 
> is it that if NODE_ENV is not set in the environment then logger uses value of development.js?

CORRECT!

2023-05-16 19:36 UTC, therj requested changes

2023-05-16 19:36 UTC, therj commented on config/default.js
> +    Level: "info",
camelCase for `FilePath` and `Level`.

2023-05-16 19:42 UTC, therj commented on config/production.js
> +    destination: "FILE",
production logs are usually set to level error, but it's your call.

2023-05-16 19:42 UTC, therj approved these changes

2023-05-16 19:43 UTC, therj commented
@samresh9, do a squash merge when you merge!

2023-05-16 19:45 UTC, samresh9 commented on config/production.js
> +    destination: "FILE",
noted

2023-05-16 19:45 UTC, merged